# Generated by Django 5.2.8 on 2025-11-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalsign',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], max_length=10),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='risk_score',
            field=models.IntegerField(default=0, help_text='Calculated risk score'),
        ),
    ]
